### PR TITLE
couch: Fix `nano` v9.x config

### LINKED ISSUE #227: [CouchDB] Name or password is incorrect.
**Describe the bug**
After upgrade to the version 1.4.18 my connection to couchdb is broken.

**To Reproduce**

Run this script:

```javascript
const ueberdb = require("ueberdb2");

const db = new ueberdb.Database("couch", {
  user: "username",
  password: "pass",
  host: "localhost",
  port: 5984,
  database: "dbname",
});

async function example(db) {
  await db.init();

  // no need for await because it's already in cache.
  db.set("valueA", { a: 1, b: 2 });

  db.get("valueA", function (err, value) {
    console.log("VALUE", value);
    // close the database connection.
    db.close(function () {
      process.exit(0);
    });
  });
}

example(db);
```

OUTPUT: 
Captura de Pantalla 2022-04-01 a la(s) 14 10 15

```
(node:86719) UnhandledPromiseRejectionWarning: Error: Name or password is incorrect.
    at responseHandler (/Users/max/Desktop/test-db/node_modules/nano/lib/nano.js:188:20)
    at /Users/max/Desktop/test-db/node_modules/nano/lib/nano.js:420:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:86719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:86719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After inspecting **databases/couch_db.js** file, the _config.auth_ values are incorrect.

Current values:

```
const config = {
      url: `http://${settings.host}:${settings.port}`,
      requestDefaults: {
        pool: {
          maxSockets: settings.maxListeners || 1,
        },
        auth: {
          user: settings.user,
          pass: settings.password,
        },
      },
    };
```

After change auth properties from _**user**_ and **_pass_** to _**username**_ and _**password**_ the connection was successfully.

```
const config = {
      url: `http://${settings.host}:${settings.port}`,
      requestDefaults: {
        pool: {
          maxSockets: settings.maxListeners || 1,
        },
        auth: {
          username: settings.user,
          password: settings.password,
        },
      },
    };
```

Captura de Pantalla 2022-04-01 a la(s) 14 14 25

PLEASE 🙏🏻 could you check that? Or what am I doing wrong?

### PR DESCRIPTION
**Pull request by rhansen**
Fixes #227

### CODE REVIEW

**Comment by zmaximo1990** [comment]
Thanks a lot @rhansen ! We'll wait for the merge to be accepted 🤓.

**Comment by zmaximo1990** [comment]
Hi @rhansen ! do you think will it be possible to release a bugfix for version 1.4.x?. That version is used on the latest version of [EtherpadLite](https://github.com/ether/etherpad-lite/blob/1.8.17/src/package.json) 🙏🏻.

Thanks in advance.

**Comment by rhansen** [comment]
@zmaximo1990 I released v2.2.1 with these changes. It is safe to run:

    cd /path/to/etherpad-lite
    cd src && npm i ueberdb2@^2.2.1

**Comment by zmaximo1990** [comment]
Thats correct @rhansen but we are using etherpad-lite repo as a submodule, so we don't want to customize any file before build the docker image. To make work your suggestion we've to overwrite Dockerfile within etherpad-lite and we wanna avoid that if it posible.

Thanks for all in advance.

**Pull request merged**
