### PR TITLE
mysql: Reconnect on fatal error and other improvements

### PR DESCRIPTION
**Pull request by rhansen**
Multiple commits:
* mysql: Promisify `close()`
* mysql: Use ES6 class syntax for readability
* mysql: Avoid adding properties to the connection object
* mysql: Reconnect on fatal error
* mysql: Add ability to set logger object
* mysql: Log MySQL errors
* mysql: Pass query values via options object
* mysql: Move timeout into `_query()`
* mysql: Separate MySQL settings from ueberdb settings
* mysql: Move default query timeout to settings
* mysql: Reschedule ping after each connect and query

cc @packardone

### CODE REVIEW

**Comment by packardone** [comment]
Thanks, Richard.  This all makes sense and looks good...

**Comment by webzwo0i** [comment]
Cool! This is extremely important work, as mysql is the mostly used database.
 I'm seeing different crashes. If you don't have time I'll try to make tests. Currently I reproduce them with:

- import a whole lot of data with etherpad-load-test
- change timeout to 10ms
- loop curl localhost:9001/getStats and start etherpad-load-test again with a lot of authors

At least three different stack traces:
bulk writes
```
    at async exports.Database.doBulk (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:207:5)
    at async exports.Database._write (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:548:7)
    at async /opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:503:9
```

gets:
```
    at async exports.Database.get (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:160:23)
    at async exports.Database._getLocked (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:306:15)
    at async exports.Database.get (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:283:12)
```

```
    at async exports.Database.findKeys (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:181:23)
    at async exports.Database.findKeys (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:350:21)
```

**Comment by webzwo0i** [comment]
https://github.com/ether/ueberDB/commit/119aed3da183422009645f6e7286aee303e06546 is a first attempt at getting test coverage. I often see `UnhandledPromiseRejectionWarning: Error: Query inactivity timeout` but not always and it's reconnecting thousands of times, so just for reference here. I couldn't find a good way to definitely reset mysql's cache. :-( Might actually be easier to skip those tests here and implement it with etherpad-load-test on etherpad directly.

**Comment by rhansen** [comment]
> I'm seeing different crashes.

I'm confused—are these crashes that would not have happened without this PR?

**Comment by webzwo0i** [comment]
No, they happen with it.

**Comment by webzwo0i** [comment]
I assume your reconnect logic is working, so now there are no "Cannot enqueue Query after fatal error" errors. But something else seems broken, all the errors I posted except the last one are from this PR. Will update the misleading section above

**Comment by rhansen** [comment]
> No, they happen with it.

Ah, OK.

> But something else seems broken, all the errors I posted except the last one are from this PR.

That's expected. There is still a lot of code that does `db.set(...)` rather than `await db.set(..)`. Before this PR, Etherpad would crash out before executing those lines, now it's living long enough to hit those.

I added a basic timeout test and fixed a race condition in `close()`. The new test doesn't test the public API (`set`, `get`, etc.) but it's better than nothing.

**Comment by webzwo0i** [comment]
Thanks for explanation. Makes sense now. Yeah, I noticed those non-awaiting db queries too when trying to find a reason for  https://github.com/ether/etherpad-lite/issues/5000 

So this is good to be merged in. (I can't do it, because I lack proper permissions on ueberDB, openid plugin and probably some other repositories). During crafting of https://github.com/ether/ueberDB/commit/119aed3da183422009645f6e7286aee303e06546 I got two or three unhandled promise rejections when directly using the public API (and one PROTOCOL_PACKETS_OUT_OF_ORDER :-D), but as said I could not reproduce them reliably so those tests are useless. I did another small test ([setting a timeout of 1ms, fire set/get/findKeys and collect them with Promise.all](https://github.com/webzwo0i/ueberDB/commit/e7b58b21b7f9aa8531028139e9d2aff08a091a5e)). I do get an  EADDRNOTAVAIL UnhandledPromiseRejectionWarning. Not sure if it is worth fixing.

Feel free to merge this PR as is.

**Pull request merged**
