### PR TITLE
deps: mongo@4.13.0

### PR DESCRIPTION
**Pull request by JohnMcLear**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
```(node:4061) [MONGODB DRIVER] Warning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.```

**Comment by JohnMcLear** [comment]
https://jira.mongodb.org/browse/COMPASS-5870

**Comment by JohnMcLear** [comment]
https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/CHANGES_4.0.0.md#intentional-breaking-changes

**Comment by SamTV12345** [comment]
Superseeded by #371 . I was faster 😄 .

**Pull request closed without merging**
