### PR TITLE
Add engine options to mysql

### PR DESCRIPTION
**Pull request by ArcticSnowman**
#115

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Shouldn't this be checking if the value exists too and if not replacing it?  
ie not setting ``this.settings.engine`` would blow shit up no?

**Comment by ArcticSnowman** [comment]
I suppose it should check that you supplied a valid table engine...   MyISAM and InnoDB?

**Comment by amartincolby** [comment]
This is especially needed with the rise of cloud RDS instances, seemingly all of which only support InnoDB. I encountered that problem just this past week on Digital Ocean.

**Comment by JohnMcLear** [comment]
Can you give me some test values I can use instead of MyISAM?

**Comment by JohnMcLear** [comment]
FWIW I put this into the rewrite.  https://github.com/ether/ueberDB/commit/90bc1a289bdedea62b0ebefdff757a10eccc2400

**Pull request closed without merging**
