### PR TITLE
sqlite: Avoid calling callbacks multiple times

### PR DESCRIPTION
**Pull request by rhansen**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Fails tests with cache on?

**Comment by JohnMcLear** [comment]
```
ERROR WITH SQL: 
BEGIN TRANSACTION;
REPLACE INTO store VALUES ('vynZtZ81CZvHG2doaUyfoovynZtZ81CZvHG2doaUy0', '{"a":1,"b":"|~5m{!{QGHQKbN>q{<K$cBeo5=/.yS#a%m#"}');
```

**Comment by rhansen** [comment]
Yeah, I know what the bug is, I'm just studying the sqlite3 code trying to determine what the proper fix is. (The sqlite3 docs aren't very good.)

**Comment by rhansen** [comment]
Should be fixed now.

**Pull request merged**
