### PR TITLE
Add mongodb support

### PR DESCRIPTION
**Pull request by Sylchauf**
Hello,

This PR add the mongodb support for ueberDB

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Nice will look at this asap

**Comment by JohnMcLear** [comment]
We're migrating from travis to github actions just FYI

**Comment by JohnMcLear** [comment]
note in test runner

```
      "before all" hook for "get of unknown key -> nullish":
     MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
```

**Comment by Sylchauf** [comment]
> note in test runner
> 
> ```
>       "before all" hook for "get of unknown key -> nullish":
>      MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
>   name: 'MongoNetworkError'
> ```

I will investigate :)

Any action needed to prepare the migration from travis to github action ?

**Comment by JohnMcLear** [comment]
Cc @rhansen

**Comment by Sylchauf** [comment]
Seems to be fixed for mongodb, but others tests still is in failure (mysql, postgre, redis) since the migration from travis to Github Action ?

I imagine that's would be fix on another PR

I remain available if there is need of any correction for mongodb

**Comment by JohnMcLear** [comment]
Yeah rhansen has a branch with the test coverage.  Just waiting for it to land.

**Comment by brunob** [comment]
Just a question, since this one was merged, is mongodb really supported ? If yes, maybe the readme should be updated to reflect that ?

**Comment by JohnMcLear** [comment]
Yes, would you please be able to send a PR updating this?

**Comment by brunob** [comment]
I should :) => #184

**Pull request merged**
